pipeline:
  name: dotNetFrameworkApp
  identifier: dotNetFrameworkApp
  projectIdentifier: FredSandBox
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: fredrepo
        repoName: SimpleFrameworkApp
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: gkefred
              namespace: payment-service-build
              initTimeout: 15m
              automountServiceAccountToken: true
              nodeSelector:
                kubernetes.io/os: windows
              os: Windows
          execution:
            steps:
              - step:
                  type: Run
                  name: msbuild
                  identifier: msbuild
                  spec:
                    connectorRef: FredDockerRegistry
                    image: mcr.microsoft.com/dotnet/framework/sdk:4.8
                    shell: Powershell
                    command: |-
                      nuget restore SimpleFrameworkApp.sln
                      msbuild SimpleFrameworkApp.sln /p:Configuration=Release
                      msbuild SimpleFrameworkApp.sln /p:Configuration=Release /p:DeployOnBuild=true /t:WebPublish /p:WebPublishMethod=FileSystem /p:publishUrl=published /p:PackageAsSingleFile=false
                      dir published
                    resources:
                      limits:
                        memory: 2G
                        cpu: "1"
                  timeout: 20m
